### ISSUE TITLE
Rebranding?

### ISSUE THREAD

**Issue by jpalczewski** [topblossom/icgbooks#1]
Literki icg to zupełnie luźna propozycja.

Ale z refaktoryzacją kodu żeby zmienić nazwę można się zajee...fajnie bawić, więc to jest decyzja do podjęcia teraz.

Propozycje, anyone?
To samo odnośnie nazwy zespołu - jak chcemy się nazywać?
Czy tbw i zostają aktualne nazwy?

**Comment by crumped** [comment]
TopBlossom jest op jako nazwa zespołu, ja propsuje :+1:  co do nazwy projektu może poczekajmy na wszystkich

**Comment by jpalczewski** [comment]
Zero reakcji, także zostajemy póki co przy aktualnej parze.
