### ISSUE TITLE
Create simple models

### ISSUE THREAD

**Issue by jpalczewski** [topblossom/icgbooks#35]
Let's don't plan too much and start simple:

informal model specification:

# user
- Display name
- Details from oAuth

# Book
- title
- pages
- author(just a string)

# readings
- user
- book
- start date optional: if null then book is marked "want to read"
- optional end date - 
- notes/category/rating

Do we need anything else?

**Comment by crumped** [comment]
Users & Books: We dont need more on this stage.
Readings: What if I read a book or books but I didn't remember exactly date (e.g. only year or year and month).
second case: What if I read a book but I don't want or I just don't remember start date? 
I think we should allow for user to set this field as optional and start date and end date should be 
independent.

**Comment by jpalczewski** [comment]
Just a side note: At this moment we can consume this info:

https://micronaut-projects.github.io/micronaut-security/1.3.1/api/io/micronaut/security/oauth2/endpoint/token/response/OpenIdClaims.html
